
require "UI.DialogLayer.BuildingOptDialogLayer"
require "UI.DialogLayer.NewBuildDialogLayer"
require "UI.DialogLayer.BuildingInfoDialogLayer"
require "UI.DialogLayer.BuildingUpgradeDialogLayer"
require "UI.DialogLayer.CampDialogLayer"
require "UI.DialogLayer.SoldierInfoDialogLayer"
require "UI.DialogLayer.HeroHotelDialogLayer"
require "UI.DialogLayer.HeroInfoDialogLayer"
require "UI.DialogLayer.ResearchLabDialogLayer"
require "UI.DialogLayer.TownDialogLayer"
require "UI.DialogLayer.GameOverDialogLayer"
